### PR TITLE
Move definition of flx-ido-mode to appease byte-compiler

### PR DESCRIPTION
**Pull request by tarsius**
Also add file "misc/.nosearch" to prevent "misc/" from being added to the `load-path`.

### CODE REVIEW

**Comment by PythonNut** [comment]
Not sure if I have the authority to merge this. 

@lewang would this make `0.6.1`?

**Comment by lewang** [comment]
My ideas around release management and the various package managers being used is lacking.  If we just merged this into master, and changed the version to something alpha [here](https://github.com/lewang/flx/blob/master/flx.el#L9) would that work?

**Comment by lewang** [comment]
And manage release through git tags?

**Comment by PythonNut** [comment]
At the moment, we don't have any sort of channel-based release system.

In any case, I would consider this a "hotfix" (like https://github.com/lewang/flx/commit/dd4b4d50dac3a55752a12aaa19498554c5d91b34, it fixes stuff that's critically broken for some), which should probably go straight to some sort of release.

**Comment by tarsius** [comment]
Thanks

**Pull request merged**
