### PR TITLE
Remove unused and deprecated ‘cl’ library

### PR DESCRIPTION
**Pull request by phst**

### CODE REVIEW

**Comment by PythonNut** [comment]
Is there a way to be sure `cl` is unused?

**Comment by oscarfv** [comment]
Given that this is a test file and hence there should be not skipped execution paths, if it runs successfully without `cl` then we can conclude that it is not required, right?

**Comment by phst** [comment]
Yes, I'm pretty sure the test would fail if the llibrary were required.

**Comment by PythonNut** [comment]
Sounds legit

**Pull request merged**
